export const EVENT_TYPES = {
  ticket: [
    { value: 'ticket.AgentAssignmentChanged', label: 'Agent Assignment Changed' },
    { value: 'ticket.AttachmentLinkedToComment', label: 'Attachment Linked To Comment' },
    { value: 'ticket.AttachmentRedactedFromComment', label: 'Attachment Redacted From Comment' },
    { value: 'ticket.BrandChanged', label: 'Brand Changed' },
    { value: 'ticket.CcsChanged', label: 'Ccs Changed' },
    { value: 'ticket.CommentAdded', label: 'Comment Added' },
    { value: 'ticket.CommentMadePrivate', label: 'Comment Made Private' },
    { value: 'ticket.CommentRedacted', label: 'Comment Redacted' },
    { value: 'ticket.CustomFieldChanged', label: 'Custom Field Changed' },
    { value: 'ticket.DescriptionChanged', label: 'Description Changed' },
    { value: 'ticket.ExternalIdChanged', label: 'External Id Changed' },
    { value: 'ticket.FollowersChanged', label: 'Followers Changed' },
    { value: 'ticket.GroupAssignmentChanged', label: 'Group Assignment Changed' },
    { value: 'ticket.MarkedAsSpam', label: 'Marked As Spam' },
    { value: 'ticket.OrganizationChanged', label: 'Organization Changed' },
    { value: 'ticket.PriorityChanged', label: 'Priority Changed' },
    { value: 'ticket.ProblemLinkChanged', label: 'Problem Link Changed' },
    { value: 'ticket.RequesterChanged', label: 'Requester Changed' },
    { value: 'ticket.StatusChanged', label: 'Status Changed' },
    { value: 'ticket.SubjectChanged', label: 'Subject Changed' },
    { value: 'ticket.SubmitterChanged', label: 'Submitter Changed' },
    { value: 'ticket.TagsChanged', label: 'Tags Changed' },
    { value: 'ticket.TaskDueAtChanged', label: 'Task Due At Changed' },
    { value: 'ticket.TicketCreated', label: 'Ticket Created' },
    { value: 'ticket.TicketFormChanged', label: 'Ticket Form Changed' },
    { value: 'ticket.TicketMerged', label: 'Ticket Merged' },
    { value: 'ticket.TicketPermanentlyDeleted', label: 'Ticket Permanently Deleted' },
    { value: 'ticket.TicketSoftDeleted', label: 'Ticket Soft Deleted' },
    { value: 'ticket.TicketTypeChanged', label: 'Ticket Type Changed' },
    { value: 'ticket.TicketUndeleted', label: 'Ticket Undeleted' },
  ],
  user: [
    { value: 'user.CustomFieldChanged', label: 'Custom Field Changed' },
    { value: 'user.CustomRoleChanged', label: 'Custom Role Changed' },
    { value: 'user.ExternalIdChanged', label: 'External Id Changed' },
    { value: 'user.LastLoginChanged', label: 'Last Login Changed' },
    { value: 'user.OnlyPrivateCommentsChanged', label: 'Only Private Comments Changed' },
    { value: 'user.TagsChanged', label: 'Tags Changed' },
    { value: 'user.TimeZoneChanged', label: 'Time Zone Changed' },
    { value: 'user.UserAliasChanged', label: 'User Alias Changed' },
    { value: 'user.UserCreated', label: 'User Created' },
    { value: 'user.UserDefaultGroupChanged', label: 'User Default Group Changed' },
    { value: 'user.UserDetailsChanged', label: 'User Details Changed' },
    { value: 'user.UserGroupAdded', label: 'User Group Added' },
    { value: 'user.UserGroupRemoved', label: 'User Group Removed' },
    { value: 'user.UserIdentityChanged', label: 'User Identity Changed' },
    { value: 'user.UserIdentityCreated', label: 'User Identity Created' },
    { value: 'user.UserIdentityRemoved', label: 'User Identity Removed' },
    { value: 'user.UserIsActiveChanged', label: 'User Is Active Changed' },
    { value: 'user.UserMerged', label: 'User Merged' },
    { value: 'user.UserNameChanged', label: 'User Name Changed' },
    { value: 'user.UserNotesChanged', label: 'User Notes Changed' },
    { value: 'user.UserOrganizationAdded', label: 'User Organization Added' },
    { value: 'user.UserOrganizationRemoved', label: 'User Organization Removed' },
    { value: 'user.UserPhotoChanged', label: 'User Photo Changed' },
    { value: 'user.UserRoleChanged', label: 'User Role Changed' },
  ],
  organization: [
    { value: 'organization.CustomFieldChanged', label: 'Custom Field Changed' },
    { value: 'organization.ExternalIdChanged', label: 'External Id Changed' },
    { value: 'organization.OrganizationCreated', label: 'Organization Created' },
    { value: 'organization.TagsChanged', label: 'Tags Changed' },
  ],
  customobject: [
    { value: 'customobject.CustomObjectRecordChanged', label: 'Custom Object Record Changed' },
    { value: 'customobject.CustomObjectRecordCreated', label: 'Custom Object Record Created' },
    { value: 'customobject.CustomObjectRecordDeleted', label: 'Custom Object Record Deleted' },
  ],
  activity: [{ value: 'activity.UserActivityCreated', label: 'User Activity Created' }],
} as const;

export type EventCategory = keyof typeof EVENT_TYPES;
export type EventType = (typeof EVENT_TYPES)[EventCategory][number];
